name: Server Passing Ruby Server Spec

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            java-version: 17
            distribution: 'adopt'
      - name: Build with Gradle
        run: PUBLIC_DIR="$(pwd)/Public/" ./gradlew build
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.5.1'
          working-directory: ./http_server_spec
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Set up Json Server
        working-directory: ./json_server
        run: npm install -g json-server
      - name: Start Json Server
        working-directory: ./json_server
        run: json-server --watch db.json &
      - name: Bundle Ruby
        working-directory: ./http_server_spec
        run: bundle install
      - name: Run the Java Http Server and shunt it to the background
        run: PUBLIC_DIR="$(pwd)/Public/" gradle run &
      - name: Run the Ruby Tests
        working-directory: ./http_server_spec
        run: bundle exec spinach
