name: ruby-server-spec

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bundle install
        run: pwd
      - name: Print Working Directory
        working-directory: ./http_server_spec
        run: pwd
