name: ruby-server-spec

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Working Directory
        run: ls
      - name: Run bundle install
        run: pwd
