name: ruby-server-spec

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: http_server_spec
    steps:
      - name: Print Working Directory
        run: pwd